const userRouter = require('./routers/userRouter')
const loginRouter = require('./routers/loginRouter')
const specializationRouter = require('./routers/specializationRouter')
const doctorRouter = require('./routers/doctorRouter')
const patientRouter = require('./routers/patientRouter')
const appointmentRouter = require('./routers/appointmentRouter')
const prescriptionRouter = require('./routers/prescriptionRouter')
const derivationRouter = require('./routers/derivationRouter')
const bodyParser = require('body-parser')
const cookieParser = require("cookie-parser");
const securityMiddleware = require('./http/middleware/securityMiddleware')
const authMiddleware = require('./http/middleware/authMiddleware')
const express = require('express')
const app = express()
app.use(bodyParser.json())
app.use(cookieParser());
app.use(authMiddleware)
app.use(securityMiddleware)
app.use('/users', userRouter)
app.use('/auth', loginRouter)
app.use('/specializations', specializationRouter)
app.use('/doctors', doctorRouter)
app.use('/patients', patientRouter)
app.use('/appointments', appointmentRouter)
app.use('/prescriptions', prescriptionRouter)
app.use('/derivations', derivationRouter)
app.listen('3000', () => {
    console.log("Server is running on port 3000")
})